---

- name: "unarchive backend"
  unarchive:
    src:   ~/project/artifact.tar.gz
    dest:  /home/ubuntu/

- name: "start pm2 "
  shell: |
    cd /home/ubuntu/
    pm2 delete all
    pm2 start npm -- start


  