---
- name: "Create backend directory"
  file:
    path: /home/ubuntu/backend_app
    state: directory

- name: "unarchive backend"
  unarchive:
    src:   ~/project/artifact.tar.gz
    dest:  /home/ubuntu/backend_app

- name: "start pm2 "
  shell: |
    cd /home/ubuntu/backend_app
    pm2 delete all
    pm2 start npm -- start


  