---

- name: Update APT packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade Packages
  become: yes
  apt:
    upgrade: yes

- name: Add node_exporter user
  become: yes
  ansible.builtin.user:
    name: node_exporter
    create_home: no

- name: Download node_exporter Package
  shell: wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz


- name: Uncompress node_exporter Package
  shell: tar xvfz node_exporter-1.0.1.linux-amd64.tar.gz

- name: Copy file to the created Directories
  become: yes
  shell: |
    sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: Push node_exporter service file
  become: yes
  copy: 
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: Reloading daemon and starting node_exporter
  become: yes
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl --now enable node-exporter     